# Site settings
title: 서브길동
description: "길동이 블로그 두번째"
baseurl: "/" # for test: remove string '/space-jekyll-template' to ''
url: "https://gildong25.github.io/subgildong.github.io/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'

# User settings
username: 길동이
user_title: 길동프로그래머
email: gildong2525@gmail.com
github_username:  gildong2525
g-analytics: UA-132672113-1
disqus_username: loremipsum
profile_picture: https://68.media.tumblr.com/93f384858e9273d5b980b418e2f2f4d5/tumblr_o5i2aybLJG1uapsfmo2_250.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/gildong2525
      new_tab: true
      key_trigger: g
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: fluany
    url: https://github.com/
  - name: vim-frontend
    url: https://github.com/
  - name: generator-capybara
    url: https://github.com/

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
